-- CRIAR USUÁRIO CURSO1 IDENFICADO PELA SENHA CURSO1
CREATE USER CURSO1 IDENTIFIED BY CURSO1;
-- CONCEDER PERMISÃO O USUÁRIO CURSO1
GRANT CONNECT, RESOURCE, CREATE VIEW TO CURSO1;
-- CRIAR DIRETÓRIO CURSOSQL DO ENDEREÇO BLABLABLA
CREATE DIRECTORY CURSOSQL as 'C:\ORACLE\DATAPUMP';

CREATE USER CRESCER15 IDENTIFIED BY CRESCER15;
GRANT CONNECT, RESOURCE, CREATE VIEW TO CRESCER15;
